insert into ${hygiene.target_database}.${hygiene.target_table} (
 time
,${hygiene.key_column}
,full_name
,prefix_title
,first_name
,middle_name
,last_name
,suffix
,gender
,address1
,address2
,locality
,region
,postal_code1
,postal_code2
,mailability_score
,dpv_status
,address_errorStatus
,address_record_type
,address_latitude
,address_longitude
,country
,person_2_fullName
,person_2_prefix
,person_2_firstName
,person_2_middleName
,person_2_lastName
,person_2_suffix
,person_2_other
,person_2_gender
,address_primaryNumber
,address_primaryPrefix1
,address_primaryName1
,address_primaryType1
,address_postfix1
,address_unitNumber
,address_unitDescription
,address_apartment
,address_ruralRouteNumber
,address_ruralRouteBox
,address_postOfficeBox
,address_foreignFlag
,address_extraneous
,address_remainder
,address_sortCode
,address_deliveryPoint
,address_checkDigit
,address_lot
,address_lotOrder
,address_dpvNoStatus
,address_dpvCmra
,address_dpvVacant
,address_dpvFtnote
,address_fipscode
,address_geographicBlock
,address_geographicMatchType
,address_match5
,address_match9
,address_matchUn
,address_rdi
,address_lacsCode
,address_lacsReturnValue
,address_ewsFlag
,address_stelinkReturnValue
,address_addressType
,address_addressQualityCode
,business_name
)
values (cast(to_unixtime(current_timestamp) as bigint)
,'${td.each.key_column}'
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_fullName1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_prefix1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_firstName1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_middleName1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_lastName1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_suffix1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_gender1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_primaryAddress"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_secondaryAddress"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_locality"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_region"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_postcode1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_postcode2"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_mailabilityScore"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_dpvStatus"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_errorStatus"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_recordType"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_latitude"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_longitude"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_countryCode"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_fullName2"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_prefix2"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_firstName2"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_middleName2"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_lastName2"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_suffix2"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_other2"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["personname_gender2"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_primaryNumber"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_primaryPrefix1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_primaryName1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_primaryType1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_postfix1"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_unitNumber"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_unitDescription"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_apartment"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_ruralRouteNumber"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_ruralRouteBox"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_postOfficeBox"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_foreignFlag"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_extraneous"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_remainder"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_sortCode"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_deliveryPoint"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_checkDigit"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_lot"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_lotOrder"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_dpvNoStatus"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_dpvCmra"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_dpvVacant"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_dpvFtnote"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_fipscode"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_geographicBlock"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_geographicMatchType"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_match5"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_match9"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_matchUn"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_rdi"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_lacsCode"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_lacsReturnValue"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_ewsFlag"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_stelinkReturnValue"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_addressType"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["address_addressQualityCode"]}','')
,NULLIF('${JSON.parse(http.last_content)["onetouchHygiene"]["business_name"]}','')
);
